### ISSUE TITLE
python nagios_silverpeak_api.py  : getting error

### ISSUE THREAD

**Issue by georgej77** [harimittapalli/nagios_silverpeak_api#1]
Hi Hari,

Im getting the below error when i run the command on nagios server. Can you provide the resolution for it.

**# python nagios_silverpeak_api.py  -H 192.168.10.211 -O tunnels**
RuntimeError: module compiled against API version 6 but this version of numpy is 4
numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "nagios_silverpeak_api.py", line 3, in <module>
    import pandas as pd
  File "/usr/lib64/python2.6/site-packages/pandas/__init__.py", line 6, in <module>
    from . import hashtable, tslib, lib
ImportError: numpy.core.multiarray failed to import
You have new mail in /var/spool/mail/root
**[root@gl-nms02 libexec]# python nagios_silverpeak_api.py  -H 192.168.10.211 -O alarms**
RuntimeError: module compiled against API version 6 but this version of numpy is 4
numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "nagios_silverpeak_api.py", line 3, in <module>
    import pandas as pd
  File "/usr/lib64/python2.6/site-packages/pandas/__init__.py", line 6, in <module>
    from . import hashtable, tslib, lib
ImportError: numpy.core.multiarray failed to import

Thanks,
JInju

**Comment by bchappe** [comment]
Hi JInju, have you found the error ?
